# How to read tabular data?

In [1]:
import pandas as pd
%matplotlib inline

In [5]:
orders=pd.read_csv('chipotle.txt',sep='\t')
orders.head()

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98

In [6]:
pd.read_csv('movieusers.txt',sep='|').head()

   1  24  M  technician  85711
0  2  53  F       other  94043
1  3  23  M      writer  32067
2  4  24  M  technician  43537
3  5  33  F       other  15213
4  6  42  M   executive  98101

In [7]:
user_cols=['user_id','age','gender','occupation','zip_code']
users=pd.read_csv('movieusers.txt',sep='|', header=None, names=user_cols)
users.head()

   user_id  age gender  occupation zip_code
0        1   24      M  technician    85711
1        2   53      F       other    94043
2        3   23      M      writer    32067
3        4   24      M  technician    43537
4        5   33      F       other    15213

In [28]:
ufo=pd.read_csv('ufo.csv')
type(ufo)

pandas.core.frame.DataFrame

In [29]:
ufo.head()

                   City Colors Reported Shape Reported State             Time
0                Ithaca             NaN       TRIANGLE    NY   6/1/1930 22:00
1           Willingboro             NaN          OTHER    NJ  6/30/1930 20:00
2               Holyoke             NaN           OVAL    CO  2/15/1931 14:00
3               Abilene             NaN           DISK    KS   6/1/1931 13:00
4  New York Worlds Fair             NaN          LIGHT    NY  4/18/1933 19:00

In [30]:
ufo['City']

0                      Ithaca
1                 Willingboro
2                     Holyoke
3                     Abilene
4        New York Worlds Fair
5                 Valley City
6                 Crater Lake
7                        Alma
8                     Eklutna
9                     Hubbard
10                    Fontana
11                   Waterloo
12                     Belton
13                     Keokuk
14                  Ludington
15                Forest Home
16                Los Angeles
17                  Hapeville
18                     Oneida
19                 Bering Sea
20                   Nebraska
21                        NaN
22                        NaN
23                  Owensboro
24                 Wilderness
25                  San Diego
26                 Wilderness
27                     Clovis
28                 Los Alamos
29               Ft. Duschene
                 ...
18211                 Holyoke
18212                  Carson
18213                Pasadena
18214                  Austin
18215                El Campo
18216            Garden Grove
18217           Berthoud Pass
18218              Sisterdale
18219            Garden Grove
18220             Shasta Lake
18221                Franklin
18222          Albrightsville
18223              Greenville
18224                 Eufaula
18225             Simi Valley
18226           San Francisco
18227           San Francisco
18228              Kingsville
18229                 Chicago
18230             Pismo Beach
18231             Pismo Beach
18232                    Lodi
18233               Anchorage
18234                Capitola
18235          Fountain Hills
18236              Grant Park
18237             Spirit Lake
18238             Eagle River
18239             Eagle River
18240                    Ybor
Name: City, Length: 18241, dtype: object

In [31]:
type(ufo['City'])

pandas.core.series.Series

In [32]:
ufo.columns

Index(['City', 'Colors Reported', 'Shape Reported', 'State', 'Time'], dtype='object')

In [33]:
ufo[['City','Time']]

                       City              Time
0                    Ithaca    6/1/1930 22:00
1               Willingboro   6/30/1930 20:00
2                   Holyoke   2/15/1931 14:00
3                   Abilene    6/1/1931 13:00
4      New York Worlds Fair   4/18/1933 19:00
5               Valley City   9/15/1934 15:30
6               Crater Lake    6/15/1935 0:00
7                      Alma    7/15/1936 0:00
8                   Eklutna  10/15/1936 17:00
9                   Hubbard    6/15/1937 0:00
10                  Fontana   8/15/1937 21:00
11                 Waterloo    6/1/1939 20:00
12                   Belton   6/30/1939 20:00
13                   Keokuk     7/7/1939 2:00
14                Ludington    6/1/1941 13:00
15              Forest Home    7/2/1941 11:30
16              Los Angeles    2/25/1942 0:00
17                Hapeville    6/1/1942 22:30
18                   Oneida    7/15/1942 1:00
19               Bering Sea   4/30/1943 23:00
20                 Nebraska    6/1/1943 15:00
21                      NaN    8/15/1943 0:00
22                      NaN    8/15/1943 0:00
23                Owensboro  10/15/1943 11:00
24               Wilderness    1/1/1944 10:00
25                San Diego    1/1/1944 12:00
26               Wilderness    1/1/1944 12:00
27                   Clovis    4/2/1944 11:00
28               Los Alamos    6/1/1944 12:00
29             Ft. Duschene   6/30/1944 10:00
...                     ...               ...
18211               Holyoke  12/28/2000 18:00
18212                Carson  12/28/2000 18:20
18213              Pasadena  12/28/2000 19:10
18214                Austin   12/29/2000 0:00
18215              El Campo   12/29/2000 9:00
18216          Garden Grove  12/29/2000 16:10
18217         Berthoud Pass  12/29/2000 19:30
18218            Sisterdale  12/29/2000 20:00
18219          Garden Grove  12/29/2000 20:30
18220           Shasta Lake  12/29/2000 20:30
18221              Franklin  12/29/2000 20:50
18222        Albrightsville  12/29/2000 21:00
18223            Greenville  12/29/2000 22:00
18224               Eufaula  12/29/2000 23:30
18225           Simi Valley  12/30/2000 10:00
18226         San Francisco  12/30/2000 22:00
18227         San Francisco  12/30/2000 22:00
18228            Kingsville   12/31/2000 4:00
18229               Chicago  12/31/2000 11:45
18230           Pismo Beach  12/31/2000 20:00
18231           Pismo Beach  12/31/2000 20:00
18232                  Lodi  12/31/2000 20:30
18233             Anchorage  12/31/2000 21:00
18234              Capitola  12/31/2000 22:00
18235        Fountain Hills  12/31/2000 23:00
18236            Grant Park  12/31/2000 23:00
18237           Spirit Lake  12/31/2000 23:00
18238           Eagle River  12/31/2000 23:45
18239           Eagle River  12/31/2000 23:45
18240                  Ybor  12/31/2000 23:59

[18241 rows x 2 columns]

In [36]:
movies = pd.read_csv('imdb.csv')
movies.head()

,star_rating,title,content_rating,genre,duration,actors_list
0,9.3,The Shawshank Redemption,R,Crime,142,"[u'Tim Robbins', u'Morgan Freeman', u'Bob Gunt..."
1,9.2,The Godfather,R,Crime,175,"[u'Marlon Brando', u'Al Pacino', u'James Caan']"
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
3,9.0,The Dark Knight,PG-13,Action,152,"[u'Christian Bale', u'Heath Ledger', u'Aaron E..."
4,8.9,Pulp Fiction,R,Crime,154,"[u'John Travolta', u'Uma Thurman', u'Samuel L...."

In [38]:
movies['title'].sort_values()

542                   (500) Days of Summer
5                             12 Angry Men
201                       12 Years a Slave
698                              127 Hours
110                  2001: A Space Odyssey
910                                   2046
596                               21 Grams
624                              25th Hour
708                       28 Days Later...
60                                3 Idiots
225                                 3-Iron
570                                    300
555                           3:10 to Yuma
427           4 Months, 3 Weeks and 2 Days
824                                     42
597                                  50/50
203                                  8 1/2
170                       A Beautiful Mind
941                       A Bridge Too Far
571                           A Bronx Tale
266                      A Christmas Story
86                      A Clockwork Orange
716                         A Few Good Men
750                    A Fish Called Wanda
276                   A Fistful of Dollars
612                     A Hard Day's Night
883                  A History of Violence
869              A Nightmare on Elm Street
865                        A Perfect World
426                              A Prophet
                      ...
207       What Ever Happened to Baby Jane?
562            What's Eating Gilbert Grape
719                When Harry Met Sally...
649                      Where Eagles Dare
33                                Whiplash
669                Who Framed Roger Rabbit
219        Who's Afraid of Virginia Woolf?
127                      Wild Strawberries
497    Willy Wonka & the Chocolate Factory
270                        Wings of Desire
483                           Withnail & I
920                                Witness
65             Witness for the Prosecution
970                            Wonder Boys
518                         Wreck-It Ralph
954                                  X-Men
248             X-Men: Days of Future Past
532                     X-Men: First Class
871                                     X2
695                      Y Tu Mama Tambien
403                             Ying xiong
235                                Yip Man
96                                 Yojimbo
280                     Young Frankenstein
535                                  Zelig
955                       Zero Dark Thirty
677                                 Zodiac
615                             Zombieland
526                                   Zulu
864                                  [Rec]
Name: title, Length: 979, dtype: object

In [40]:
movies.sort_values('duration')

,star_rating,title,content_rating,genre,duration,actors_list
389,8.0,Freaks,UNRATED,Drama,64,"[u'Wallace Ford', u'Leila Hyams', u'Olga Bacla..."
338,8.0,Battleship Potemkin,UNRATED,History,66,"[u'Aleksandr Antonov', u'Vladimir Barsky', u'G..."
258,8.1,The Cabinet of Dr. Caligari,UNRATED,Crime,67,"[u'Werner Krauss', u'Conrad Veidt', u'Friedric..."
293,8.1,Duck Soup,PASSED,Comedy,68,"[u'Groucho Marx', u'Harpo Marx', u'Chico Marx']"
88,8.4,The Kid,NOT RATED,Comedy,68,"[u'Charles Chaplin', u'Edna Purviance', u'Jack..."
742,7.6,Following,R,Mystery,69,"[u'Jeremy Theobald', u'Alex Haw', u'Lucy Russe..."
351,8.0,Frankenstein,UNRATED,Horror,70,"[u'Colin Clive', u'Mae Clarke', u'Boris Karloff']"
938,7.4,Alice in Wonderland,G,Animation,75,"[u'Kathryn Beaumont', u'Ed Wynn', u'Richard Ha..."
405,7.9,The Bride of Frankenstein,NOT RATED,Horror,75,"[u'Boris Karloff', u'Elsa Lanchester', u'Colin..."
303,8.0,The Nightmare Before Christmas,PG,Animation,76,"[u'Danny Elfman', u'Chris Sarandon', u""Catheri..."
713,7.6,The Jungle Book,APPROVED,Animation,78,"[u'Phil Harris', u'Sebastian Cabot', u'Louis P..."
864,7.5,[Rec],R,Horror,78,"[u'Manuela Velasco', u'Ferran Terraza', u'Jorg..."
489,7.8,The Triplets of Belleville,PG-13,Animation,78,"[u'Mich\xe8le Caucheteux', u'Jean-Claude Donda..."
535,7.8,Zelig,PG,Comedy,79,"[u'Woody Allen', u'Mia Farrow', u'Patrick Horg..."
513,7.8,Invasion of the Body Snatchers,APPROVED,Horror,80,"[u'Kevin McCarthy', u'Dana Wynter', u'Larry Ga..."
853,7.5,L'illusionniste,PG,Animation,80,"[u'Jean-Claude Donda', u'Eilidh Rankin', u'Dun..."
533,7.8,Run Lola Run,R,Action,80,"[u'Franka Potente', u'Moritz Bleibtreu', u'Her..."
283,8.1,Before Sunset,R,Drama,80,"[u'Ethan Hawke', u'Julie Delpy', u'Vernon Dobt..."
297,8.0,Rope,PG,Crime,80,"[u'James Stewart', u'John Dall', u'Farley Gran..."
622,7.7,The Dinner Game,PG-13,Comedy,80,"[u'Thierry Lhermitte', u'Jacques Villeret', u'..."
117,8.3,Toy Story,G,Animation,81,"[u'Tom Hanks', u'Tim Allen', u'Don Rickles']"
541,7.8,South Park: Bigger Longer & Uncut,R,Animation,81,"[u'Trey Parker', u'Matt Stone', u'Mary Kay Ber..."
738,7.6,Army of Darkness,R,Comedy,81,"[u'Bruce Campbell', u'Embeth Davidtz', u'Marcu..."
789,7.6,Ice Age,PG,Animation,81,"[u'Denis Leary', u'John Leguizamo', u'Ray Roma..."
330,8.0,Nosferatu,UNRATED,Horror,81,"[u'Max Schreck', u'Greta Schr\xf6der', u'Ruth ..."
595,7.7,The Purple Rose of Cairo,PG,Comedy,82,"[u'Mia Farrow', u'Jeff Daniels', u'Danny Aiello']"
306,8.0,This Is Spinal Tap,R,Comedy,82,"[u'Rob Reiner', u'Michael McKean', u'Christoph..."
174,8.2,Persona,NOT RATED,Drama,83,"[u'Bibi Andersson', u'Liv Ullmann', u'Margaret..."
759,7.6,Robin Hood,G,Animation,83,"[u'Brian Bedford', u'Phil Harris', u'Roger Mil..."
766,7.6,The Little Mermaid,G,Animation,83,"[u'Jodi Benson', u'Samuel E. Wright', u'Rene A..."
...,...,...,...,...,...,...
361,8.0,Fiddler on the Roof,G,Drama,181,"[u'Topol', u'Norma Crane', u'Leonard Frey']"
166,8.2,The Deer Hunter,R,Drama,182,"[u'Robert De Niro', u'Christopher Walken', u'J..."
109,8.3,Dil Chahta Hai,NOT RATED,Comedy,183,"[u'Aamir Khan', u'Saif Ali Khan', u'Akshaye Kh..."
245,8.1,Barry Lyndon,PG,Adventure,184,"[u""Ryan O'Neal"", u'Marisa Berenson', u'Patrick..."
132,8.3,Judgment at Nuremberg,NOT RATED,Drama,186,"[u'Spencer Tracy', u'Burt Lancaster', u'Richar..."
611,7.7,Short Cuts,R,Comedy,187,"[u'Andie MacDowell', u'Julianne Moore', u'Tim ..."
318,8.0,Magnolia,R,Drama,188,"[u'Tom Cruise', u'Jason Robards', u'Julianne M..."
184,8.2,Fanny and Alexander,R,Drama,188,"[u'Bertil Guve', u'Pernilla Allwin', u'Kristin..."
89,8.4,Swades,NOT RATED,Drama,189,"[u'Shah Rukh Khan', u'Gayatri Joshi', u'Kishor..."
316,8.0,JFK,R,Drama,189,"[u'Kevin Costner', u'Gary Oldman', u'Jack Lemm..."
40,8.5,The Green Mile,R,Crime,189,"[u'Tom Hanks', u'Michael Clarke Duncan', u'Dav..."
671,7.7,Grindhouse,R,Action,191,"[u'Kurt Russell', u'Rose McGowan', u'Danny Tre..."
220,8.1,Gandhi,PG,Biography,191,"[u'Ben Kingsley', u'John Gielgud', u'Candice B..."
424,7.9,The Right Stuff,R,Adventure,193,"[u'Sam Shepard', u'Scott Glenn', u'Ed Harris']"
620,7.7,Titanic,PG-13,Drama,194,"[u'Leonardo DiCaprio', u'Kate Winslet', u'Bill..."
8,8.9,Schindler's List,R,Biography,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings..."
385,8.0,Spartacus,PG-13,Action,197,"[u'Kirk Douglas', u'Laurence Olivier', u'Jean ..."
335,8.0,Doctor Zhivago,PG-13,Drama,197,"[u'Omar Sharif', u'Julie Christie', u'Geraldin..."
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
630,7.7,Malcolm X,PG-13,Biography,202,"[u'Denzel Washington', u'Angela Bassett', u'De..."
767,7.6,"It's a Mad, Mad, Mad, Mad World",APPROVED,Action,205,"[u'Spencer Tracy', u'Milton Berle', u'Ethel Me..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
204,8.1,Ben-Hur,G,Adventure,212,"[u'Charlton Heston', u'Jack Hawkins', u'Stephe..."
85,8.4,Lawrence of Arabia,PG,Adventure,216,"[u""Peter O'Toole"", u'Alec Guinness', u'Anthony..."
445,7.9,The Ten Commandments,APPROVED,Adventure,220,"[u'Charlton Heston', u'Yul Brynner', u'Anne Ba..."
142,8.3,Lagaan: Once Upon a Time in India,PG,Adventure,224,"[u'Aamir Khan', u'Gracy Singh', u'Rachel Shell..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
157,8.2,Gone with the Wind,G,Drama,238,"[u'Clark Gable', u'Vivien Leigh', u'Thomas Mit..."
476,7.8,Hamlet,PG-13,Drama,242,"[u'Kenneth Branagh', u'Julie Christie', u'Dere..."

In [43]:
movies.sort_values('duration', ascending = False)

,star_rating,title,content_rating,genre,duration,actors_list
476,7.8,Hamlet,PG-13,Drama,242,"[u'Kenneth Branagh', u'Julie Christie', u'Dere..."
157,8.2,Gone with the Wind,G,Drama,238,"[u'Clark Gable', u'Vivien Leigh', u'Thomas Mit..."
78,8.4,Once Upon a Time in America,R,Crime,229,"[u'Robert De Niro', u'James Woods', u'Elizabet..."
142,8.3,Lagaan: Once Upon a Time in India,PG,Adventure,224,"[u'Aamir Khan', u'Gracy Singh', u'Rachel Shell..."
445,7.9,The Ten Commandments,APPROVED,Adventure,220,"[u'Charlton Heston', u'Yul Brynner', u'Anne Ba..."
85,8.4,Lawrence of Arabia,PG,Adventure,216,"[u""Peter O'Toole"", u'Alec Guinness', u'Anthony..."
204,8.1,Ben-Hur,G,Adventure,212,"[u'Charlton Heston', u'Jack Hawkins', u'Stephe..."
17,8.7,Seven Samurai,UNRATED,Drama,207,"[u'Toshir\xf4 Mifune', u'Takashi Shimura', u'K..."
767,7.6,"It's a Mad, Mad, Mad, Mad World",APPROVED,Action,205,"[u'Spencer Tracy', u'Milton Berle', u'Ethel Me..."
630,7.7,Malcolm X,PG-13,Biography,202,"[u'Denzel Washington', u'Angela Bassett', u'De..."
7,8.9,The Lord of the Rings: The Return of the King,PG-13,Adventure,201,"[u'Elijah Wood', u'Viggo Mortensen', u'Ian McK..."
2,9.1,The Godfather: Part II,R,Crime,200,"[u'Al Pacino', u'Robert De Niro', u'Robert Duv..."
335,8.0,Doctor Zhivago,PG-13,Drama,197,"[u'Omar Sharif', u'Julie Christie', u'Geraldin..."
385,8.0,Spartacus,PG-13,Action,197,"[u'Kirk Douglas', u'Laurence Olivier', u'Jean ..."
8,8.9,Schindler's List,R,Biography,195,"[u'Liam Neeson', u'Ralph Fiennes', u'Ben Kings..."
620,7.7,Titanic,PG-13,Drama,194,"[u'Leonardo DiCaprio', u'Kate Winslet', u'Bill..."
424,7.9,The Right Stuff,R,Adventure,193,"[u'Sam Shepard', u'Scott Glenn', u'Ed Harris']"
220,8.1,Gandhi,PG,Biography,191,"[u'Ben Kingsley', u'John Gielgud', u'Candice B..."
671,7.7,Grindhouse,R,Action,191,"[u'Kurt Russell', u'Rose McGowan', u'Danny Tre..."
89,8.4,Swades,NOT RATED,Drama,189,"[u'Shah Rukh Khan', u'Gayatri Joshi', u'Kishor..."
40,8.5,The Green Mile,R,Crime,189,"[u'Tom Hanks', u'Michael Clarke Duncan', u'Dav..."
316,8.0,JFK,R,Drama,189,"[u'Kevin Costner', u'Gary Oldman', u'Jack Lemm..."
184,8.2,Fanny and Alexander,R,Drama,188,"[u'Bertil Guve', u'Pernilla Allwin', u'Kristin..."
318,8.0,Magnolia,R,Drama,188,"[u'Tom Cruise', u'Jason Robards', u'Julianne M..."
611,7.7,Short Cuts,R,Comedy,187,"[u'Andie MacDowell', u'Julianne Moore', u'Tim ..."
132,8.3,Judgment at Nuremberg,NOT RATED,Drama,186,"[u'Spencer Tracy', u'Burt Lancaster', u'Richar..."
245,8.1,Barry Lyndon,PG,Adventure,184,"[u""Ryan O'Neal"", u'Marisa Berenson', u'Patrick..."
109,8.3,Dil Chahta Hai,NOT RATED,Comedy,183,"[u'Aamir Khan', u'Saif Ali Khan', u'Akshaye Kh..."
166,8.2,The Deer Hunter,R,Drama,182,"[u'Robert De Niro', u'Christopher Walken', u'J..."
93,8.4,Dilwale Dulhania Le Jayenge,NOT RATED,Comedy,181,"[u'Shah Rukh Khan', u'Kajol', u'Amrish Puri']"
...,...,...,...,...,...,...
881,7.5,The Texas Chain Saw Massacre,R,Horror,83,"[u'Marilyn Burns', u'Edwin Neal', u'Allen Danz..."
766,7.6,The Little Mermaid,G,Animation,83,"[u'Jodi Benson', u'Samuel E. Wright', u'Rene A..."
174,8.2,Persona,NOT RATED,Drama,83,"[u'Bibi Andersson', u'Liv Ullmann', u'Margaret..."
306,8.0,This Is Spinal Tap,R,Comedy,82,"[u'Rob Reiner', u'Michael McKean', u'Christoph..."
595,7.7,The Purple Rose of Cairo,PG,Comedy,82,"[u'Mia Farrow', u'Jeff Daniels', u'Danny Aiello']"
738,7.6,Army of Darkness,R,Comedy,81,"[u'Bruce Campbell', u'Embeth Davidtz', u'Marcu..."
541,7.8,South Park: Bigger Longer & Uncut,R,Animation,81,"[u'Trey Parker', u'Matt Stone', u'Mary Kay Ber..."
117,8.3,Toy Story,G,Animation,81,"[u'Tom Hanks', u'Tim Allen', u'Don Rickles']"
789,7.6,Ice Age,PG,Animation,81,"[u'Denis Leary', u'John Leguizamo', u'Ray Roma..."
330,8.0,Nosferatu,UNRATED,Horror,81,"[u'Max Schreck', u'Greta Schr\xf6der', u'Ruth ..."
853,7.5,L'illusionniste,PG,Animation,80,"[u'Jean-Claude Donda', u'Eilidh Rankin', u'Dun..."
297,8.0,Rope,PG,Crime,80,"[u'James Stewart', u'John Dall', u'Farley Gran..."
283,8.1,Before Sunset,R,Drama,80,"[u'Ethan Hawke', u'Julie Delpy', u'Vernon Dobt..."
513,7.8,Invasion of the Body Snatchers,APPROVED,Horror,80,"[u'Kevin McCarthy', u'Dana Wynter', u'Larry Ga..."
533,7.8,Run Lola Run,R,Action,80,"[u'Franka Potente', u'Moritz Bleibtreu', u'Her..."
622,7.7,The Dinner Game,PG-13,Comedy,80,"[u'Thierry Lhermitte', u'Jacques Villeret', u'..."
535,7.8,Zelig,PG,Comedy,79,"[u'Woody Allen', u'Mia Farrow', u'Patrick Horg..."
489,7.8,The Triplets of Belleville,PG-13,Animation,78,"[u'Mich\xe8le Caucheteux', u'Jean-Claude Donda..."
864,7.5,[Rec],R,Horror,78,"[u'Manuela Velasco', u'Ferran Terraza', u'Jorg..."
713,7.6,The Jungle Book,APPROVED,Animation,78,"[u'Phil Harris', u'Sebastian Cabot', u'Louis P..."
303,8.0,The Nightmare Before Christmas,PG,Animation,76,"[u'Danny Elfman', u'Chris Sarandon', u""Catheri..."
405,7.9,The Bride of Frankenstein,NOT RATED,Horror,75,"[u'Boris Karloff', u'Elsa Lanchester', u'Colin..."
938,7.4,Alice in Wonderland,G,Animation,75,"[u'Kathryn Beaumont', u'Ed Wynn', u'Richard Ha..."
351,8.0,Frankenstein,UNRATED,Horror,70,"[u'Colin Clive', u'Mae Clarke', u'Boris Karloff']"
742,7.6,Following,R,Mystery,69,"[u'Jeremy Theobald', u'Alex Haw', u'Lucy Russe..."
293,8.1,Duck Soup,PASSED,Comedy,68,"[u'Groucho Marx', u'Harpo Marx', u'Chico Marx']"
88,8.4,The Kid,NOT RATED,Comedy,68,"[u'Charles Chaplin', u'Edna Purviance', u'Jack..."
258,8.1,The Cabinet of Dr. Caligari,UNRATED,Crime,67,"[u'Werner Krauss', u'Conrad Veidt', u'Friedric..."
338,8.0,Battleship Potemkin,UNRATED,History,66,"[u'Aleksandr Antonov', u'Vladimir Barsky', u'G..."
389,8.0,Freaks,UNRATED,Drama,64,"[u'Wallace Ford', u'Leila Hyams', u'Olga Bacla..."